version: '3.7'

services:
  web:
    build: ./atados
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./atados/:/usr/src/atados/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senha
      - POSTGRES_DB=atados

volumes:
  postgres_data: