# Generated by Django 3.1.1 on 2020-09-18 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Informe o nome da Ação', verbose_name='Nome da Ação')),
                ('institute', models.TextField(help_text='Instituição organizadora da ação', verbose_name='Instituição')),
                ('address', models.TextField(help_text='Local da ação (cidade, bairro e endereço)', verbose_name='Local da Ação')),
                ('description', models.TextField(help_text='Conte um pouco de como será a ação', verbose_name='Descrição da Ação')),
                ('volunteer', models.ForeignKey(help_text='Loan Client', on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
