# Generated by Django 3.1.1 on 2020-09-18 03:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='action',
            name='volunteer',
            field=models.ManyToManyField(help_text='Voluntários', related_name='volunteers', to=settings.AUTH_USER_MODEL),
        ),
    ]
